name: zhuiminzhenshi
on:
  workflow_dispatch:

  schedule:
    - cron: '39 4,10,16,22 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhuiminzhenshi
        env:
          lj71533: ${{ secrets.lj71533 }}
        run: |
          printf '%s' "$lj71533" | jq -r .fzzp389 | /bin/bash
          echo $yrwb07 | jq -r .cpg724 | /bin/bash
          echo $sqduq0629 | jq -r .ttl1316 | /bin/bash
          echo $kkdu0 | jq -r .nvko5 | /bin/bash
          printf '%s' "$m69547" | jq -r .henjs900 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ln4SBGJ3
          path: "*.zip"
          retention-days: 1
